<a href="https://colab.research.google.com/github/Iqbalnm786/DATA-SCIENCE-PANDAS-NUMPY-MATPLOTLIB-/blob/main/Basic_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **`*Basic numpy Operations*`**

---



In [4]:
# 1. np.array()
# ➤ Purpose: Creates a NumPy array from a list or tuple.
# ➤ Example:
# arr = np.array([1, 2, 3])
# 🔍 Why Use It: It’s the foundation of NumPy — much faster than Python lists.

import numpy as np
arr=np.array([1,2,3])
arr


array([1, 2, 3])

In [6]:
# 2. np.arange()
# ➤ Purpose: Creates a range of values with a step.
# ➤ Example:
# np.arange(1, 10, 2)
# 🔍 Why Use It: Useful for loops, indexing, or generating numeric sequences.


np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [7]:
# 3. np.linspace()
# ➤ Purpose: Generates evenly spaced values between a start and end.
# ➤ Example:
# np.linspace(0, 1, 5)
# 🔍 Why Use It: Best for graphs, simulations, and sampling.

np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [11]:
# 4. np.zeros()
# ➤ Purpose: Creates an array of zeros.
# ➤ Example:
# np.zeros((3,3))
# 🔍 Why Use It: For initializing matrices before filling data.

np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [14]:
# 5. np.ones()
# ➤ Purpose: Creates an array of ones.
# ➤ Example:
# np.ones(5)
# 🔍 Why Use It: Good for placeholders or constants.

np.ones(5)

array([1., 1., 1., 1., 1.])

In [15]:
# 6. np.eye()
# ➤ Purpose: Generates an identity matrix.
# ➤ Example:
# np.eye(4)
# 🔍 Why Use It: Important in algebra, ML, and matrix calculations.

np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [28]:
# 7. np.reshape()
# ➤ Purpose: Changes array shape without changing the data.
# ➤ Example:
# arr.reshape(2, 3)
# 🔍 Why Use It: Useful in ML models (inputs reshape).
arr = np.array([1, 2, 3,5,8,10])
arr.reshape(3,2)


array([[ 1,  2],
       [ 3,  5],
       [ 8, 10]])

In [29]:
# 8. np.sum()
# ➤ Purpose: Adds all elements.
# ➤ Example:
# np.sum(arr)
# 🔍 Why Use It: Basic but essential for calculations.

np.sum(arr)

np.int64(29)

In [30]:
# 9. np.mean()
# ➤ Purpose: Calculates average value.
# ➤ Example:
# np.mean(arr)

np.mean(arr)

np.float64(4.833333333333333)

In [31]:
# 10. np.std()
# ➤ Purpose: Computes standard deviation.
# ➤ Example:
# np.std(arr)
# 🔍 Why Use It: Measures data spread.

np.std(arr)


np.float64(3.2360813064912666)

In [37]:
# 11. np.min() / np.max()
# ➤ Purpose: Finds smallest or largest value.
# ➤ Example:
# np.max(arr)

np.min(arr)

np.int64(1)

In [35]:
np.max(arr)

np.int64(10)

In [70]:
# 12. np.random.rand()
# ➤ Purpose: Generates random numbers between 0 and 1.
# ➤ Example:
# np.random.rand(3)

np.random.rand(3,2)

array([[0.545719  , 0.05959809],
       [0.33313553, 0.81658447],
       [0.98430617, 0.41910458]])

In [108]:
# 13. np.random.randint()
# ➤ Purpose: Random integers in a specified range.
# ➤ Example:
# np.random.randint(1, 100)
# 🔍 Why Use It: Used in games, ML random sampling.

np.random.randint(1,100)


28

In [113]:
# 14. np.concatenate()
# ➤ Purpose: Combines arrays.
# ➤ Example:
# np.concatenate([a, b])
# 🔍 Why Use It: Merging datasets.
a=([4,5,6,5])
b=([8,6,7,5])
np.concatenate([a,b])


array([4, 5, 6, 5, 8, 6, 7, 5])

In [116]:
# 15. np.unique()
# ➤ Purpose: Returns unique elements.
# ➤ Example:
# np.unique(arr)

arr=([1,1,5,5,4,4,9,10])
np.unique(arr)

array([ 1,  4,  5,  9, 10])

In [118]:
# 16. np.sort()
# ➤ Purpose: Sorts an array.
# ➤ Example:
# np.sort(arr)
# 🔍 Why Use It: Ordering data

arr=([4,8,8,2,9,1,20])
np.sort(arr)

array([ 1,  2,  4,  8,  8,  9, 20])

In [133]:
# 17. Array Indexing (arr[ ], arr[:, ])
# ➤ Purpose: Access specific rows, columns and slices.
# ➤ Example:
# arr[0]
# arr[:, 1]
# 🔍 Why Use It: Ultra-fast data access — essential in ML.

arr=np.array([[4,8,2,9,1,20]])

print(arr[:,5])

[20]


In [146]:
# 18. np.where()
# ➤ Purpose: Returns positions where condition is true.
# ➤ Example:
# np.where(arr > 10)
arr=np.array([4,8,2,9,1,20])
np.where(arr > 2)

(array([0, 1, 3, 5]),)

In [147]:
# 19. np.dot()
# ➤ Purpose: Matrix multiplication / dot product.
# ➤ Example:
# np.dot(a, b)

a=8
b=7
np.dot(a,b)

np.int64(56)

In [153]:
# 20. np.transpose() / arr.T
# ➤ Purpose: Swaps rows and columns.
# ➤ Example:
# arr.T
# 🔍 Why Use It: Required in ML pipelines & data reshaping.

arr.T

array([ 4,  8,  2,  9,  1, 20])