<a href="https://colab.research.google.com/github/Iqbalnm786/DATA-SCIENCE-PANDAS-NUMPY-MATPLOTLIB-/blob/main/numpy_with_dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ***Numpy-Using-Dataset***

---



In [15]:
import numpy as np
import random
import pandas as pd

df = pd.read_csv('/content/weather_data- Numpy 1st assesment.csv')
df

Day  Temperature  Humidity
0    1           29        68
1    2           31        72
2    3           33        70
3    4           30        75
4    5           28        65
5    6           27        63
6    7           32        71

In [16]:
# 1️⃣ Create a 2D array combining Temperature and Humidity
# ➤ Use np.array() and arrange as rows or columns.

x=df['Temperature']
y=df['Humidity']
arr=np.array([x,y])
arr

array([[29, 31, 33, 30, 28, 27, 32],
       [68, 72, 70, 75, 65, 63, 71]])

In [17]:
# 2️⃣ Generate an array of missing days from 1 to 10
# ➤ Use np.arange(1, 11)
# (Hint: You only have days 1 to 7)

m=np.arange(1,11)
n=np.arange(1,8)
np.arange(1,11)
nm=np.setdiff1d(m,n)
nm

array([ 8,  9, 10])

In [18]:
# 3️⃣ Create 5 evenly spaced test values between min & max temperature
# ➤ Use np.linspace()
np.linspace(np.min(arr[0]),np.max(arr[0]),5)


array([27. , 28.5, 30. , 31.5, 33. ])

In [19]:
# 4️⃣ Create a 7×1 array of zeros and ones
# ➤ Use np.zeros() and np.ones()

np.zeros((7,1))

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [20]:
np.ones((7,1))

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [21]:
# 5️⃣ Reshape temperature into a 7×1 matrix
# ➤ Use np.reshape(7,1)

x=arr[0]
x.reshape(7,1)

array([[29],
       [31],
       [33],
       [30],
       [28],
       [27],
       [32]])

In [22]:

# 6️⃣ Calculate the following for temperature:
# Sum
# Mean
# Max
# Min
# ➤ Use np.sum(), np.mean(), np.max(), np.min()

x=arr[0]
x.sum()

np.int64(210)

In [23]:
x=arr[0]
x.mean()

np.float64(30.0)

In [24]:
x=arr[0]
x.max()

np.int64(33)

In [25]:
x=arr[0]
x.min()

np.int64(27)

In [26]:
# 7️⃣ Sort humidity values
# ➤ Use np.sort()

y=arr[1]
y.sort()
y

array([63, 65, 68, 70, 71, 72, 75])

In [28]:
# 8️⃣ Generate 7 random humidity errors between -3 and +3
# ➤ Use np.random.randint(-3, 4, 7)
np.random.randint(-3,4,7)


array([ 3, -2, -3,  2, -3,  0, -1])

In [30]:
# 9️⃣ Generate 7 random temperature fluctuations (0-1 range)
# ➤ Use np.random.rand(7)

np.random.rand(7)

array([0.33377122, 0.3853146 , 0.04780612, 0.64343714, 0.00797022,
       0.30313823, 0.40128932])

In [32]:
# 🔟 Find unique humidity values
# ➤ Use np.unique()

np.unique(y)

array([63, 65, 68, 70, 71, 72, 75])

In [37]:
# 1️⃣1️⃣ Combine temperature and humidity into a single long array
# ➤ Use np.concatenate()

np.concatenate(([x,y]))

array([29, 31, 33, 30, 28, 27, 32, 63, 65, 68, 70, 71, 72, 75])

In [40]:
# 1️⃣2️⃣ Create a 7×2 weather matrix and find humidity column
# weather = np.array([temperature, humidity])

weather = np.array([x,y])
weather.reshape(7,2)




array([[29, 31],
       [33, 30],
       [28, 27],
       [32, 63],
       [65, 68],
       [70, 71],
       [72, 75]])

In [43]:
# 1️⃣3️⃣ Find temperatures greater than 30°C
# ➤ Use np.where(temperature > 30)

np.where(x>30)

(array([1, 2, 6]),)

In [46]:
# 1️⃣4️⃣ Transpose the weather matrix
# ➤ Use matrix.T

weather.T


array([[29, 63],
       [31, 65],
       [33, 68],
       [30, 70],
       [28, 71],
       [27, 72],
       [32, 75]])

In [48]:
# 1️⃣5️⃣ Perform dot product: Temperature × Humidity (element-wise sum)
# Hint:
# You first need reshaping to valid dimensions.
# ➤ Use np.dot()

np.dot(x,y)



np.int64(14518)

In [52]:
# 1️⃣6️⃣ Create an identity matrix of size 3
# ➤ Use np.eye(3)
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [53]:
# # 1️⃣7️⃣ Create a 3×3 grid of ones for weather testing
# ➤ Use np.ones((3,3))


np.ones((3,3))


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [54]:
# 1️⃣8️⃣ Slice the first 4 days humidity
# ➤ Use humidity[:4]

y[:4]

array([63, 65, 68, 70])

In [56]:
# 1️⃣9️⃣ Slice the last 3 temperature values
# ➤ Use temperature[-3:]

x[-3:]

array([28, 27, 32])

In [57]:
# 2️⃣0️⃣ Compare humidity > 70 and display all such days
# ➤ Use np.where()

np.where(y>70)

(array([4, 5, 6]),)